version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/app

  microservice:
    build:
      context: ./microservice
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./microservice:/app

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: monitorasom_user
      POSTGRES_PASSWORD: monitorasom_password
      POSTGRES_DB: monitorasom_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: